export type CountryCodesType = {
  "dial code": string;
  flag: string;
  "alpha-2": string;
  name: string;
};

export const CountryCodes: CountryCodesType[] = [
  {
    "dial code": "+1",
    flag: "🇨🇦",
    "alpha-2": "CA",
    name: "Canada",
  },
  {
    "dial code": "+1",
    flag: "🇺🇸",
    "alpha-2": "US",
    name: "United States",
  },
  {
    "dial code": "+1242",
    flag: "🇧🇸",
    "alpha-2": "BS",
    name: "Bahamas",
  },
  {
    "dial code": "+1246",
    flag: "🇧🇧",
    "alpha-2": "BB",
    name: "Barbados",
  },
  {
    "dial code": "+1264",
    flag: "🇦🇮",
    "alpha-2": "AI",
    name: "Anguilla",
  },
  {
    "dial code": "+1268",
    flag: "🇦🇬",
    "alpha-2": "AG",
    name: "Antigua and Barbuda",
  },
  {
    "dial code": "+1284",
    flag: "🇻🇬",
    "alpha-2": "VG",
    name: "Virgin Islands",
  },
  {
    "dial code": "+1340",
    flag: "🇻🇮",
    "alpha-2": "VI",
    name: "Virgin Islands",
  },
  {
    "dial code": "+1441",
    flag: "🇧🇲",
    "alpha-2": "BM",
    name: "Bermuda",
  },
  {
    "dial code": "+1473",
    flag: "🇬🇩",
    "alpha-2": "GD",
    name: "Grenada",
  },
  {
    "dial code": "+1649",
    flag: "🇹🇨",
    "alpha-2": "TC",
    name: "Turks and Caicos Islands",
  },
  {
    "dial code": "+1664",
    flag: "🇲🇸",
    "alpha-2": "MS",
    name: "Montserrat",
  },
  {
    "dial code": "+1670",
    flag: "🇲🇵",
    "alpha-2": "MP",
    name: "Northern Mariana Islands",
  },
  {
    "dial code": "+1671",
    flag: "🇬🇺",
    "alpha-2": "GU",
    name: "Guam",
  },
  {
    "dial code": "+1684",
    flag: "🇦🇸",
    "alpha-2": "AS",
    name: "American Samoa",
  },
  {
    "dial code": "+1758",
    flag: "🇱🇨",
    "alpha-2": "LC",
    name: "Saint Lucia",
  },
  {
    "dial code": "+1767",
    flag: "🇩🇲",
    "alpha-2": "DM",
    name: "Dominica",
  },
  {
    "dial code": "+1784",
    flag: "🇻🇨",
    "alpha-2": "VC",
    name: "Saint Vincent and the Grenadines",
  },
  {
    "dial code": "+1849",
    flag: "🇩🇴",
    "alpha-2": "DO",
    name: "Dominican Republic",
  },
  {
    "dial code": "+1868",
    flag: "🇹🇹",
    "alpha-2": "TT",
    name: "Trinidad and Tobago",
  },
  {
    "dial code": "+1869",
    flag: "🇰🇳",
    "alpha-2": "KN",
    name: "Saint Kitts and Nevis",
  },
  {
    "dial code": "+1876",
    flag: "🇯🇲",
    "alpha-2": "JM",
    name: "Jamaica",
  },
  {
    "dial code": "+1939",
    flag: "🇵🇷",
    "alpha-2": "PR",
    name: "Puerto Rico",
  },
  {
    "dial code": "+20",
    flag: "🇪🇬",
    "alpha-2": "EG",
    name: "Egypt",
  },
  {
    "dial code": "+211",
    flag: "🇸🇸",
    "alpha-2": "SS",
    name: "South Sudan",
  },
  {
    "dial code": "+212",
    flag: "🇲🇦",
    "alpha-2": "MA",
    name: "Morocco",
  },
  {
    "dial code": "+213",
    flag: "🇩🇿",
    "alpha-2": "DZ",
    name: "Algeria",
  },
  {
    "dial code": "+216",
    flag: "🇹🇳",
    "alpha-2": "TN",
    name: "Tunisia",
  },
  {
    "dial code": "+218",
    flag: "🇱🇾",
    "alpha-2": "LY",
    name: "Libyan Arab Jamahiriya",
  },
  {
    "dial code": "+220",
    flag: "🇬🇲",
    "alpha-2": "GM",
    name: "Gambia",
  },
  {
    "dial code": "+221",
    flag: "🇸🇳",
    "alpha-2": "SN",
    name: "Senegal",
  },
  {
    "dial code": "+222",
    flag: "🇲🇷",
    "alpha-2": "MR",
    name: "Mauritania",
  },
  {
    "dial code": "+223",
    flag: "🇲🇱",
    "alpha-2": "ML",
    name: "Mali",
  },
  {
    "dial code": "+224",
    flag: "🇬🇳",
    "alpha-2": "GN",
    name: "Guinea",
  },
  {
    "dial code": "+225",
    flag: "🇨🇮",
    "alpha-2": "CI",
    name: "Cote d'Ivoire",
  },
  {
    "dial code": "+226",
    flag: "🇧🇫",
    "alpha-2": "BF",
    name: "Burkina Faso",
  },
  {
    "dial code": "+227",
    flag: "🇳🇪",
    "alpha-2": "NE",
    name: "Niger",
  },
  {
    "dial code": "+228",
    flag: "🇹🇬",
    "alpha-2": "TG",
    name: "Togo",
  },
  {
    "dial code": "+229",
    flag: "🇧🇯",
    "alpha-2": "BJ",
    name: "Benin",
  },
  {
    "dial code": "+230",
    flag: "🇲🇺",
    "alpha-2": "MU",
    name: "Mauritius",
  },
  {
    "dial code": "+231",
    flag: "🇱🇷",
    "alpha-2": "LR",
    name: "Liberia",
  },
  {
    "dial code": "+232",
    flag: "🇸🇱",
    "alpha-2": "SL",
    name: "Sierra Leone",
  },
  {
    "dial code": "+233",
    flag: "🇬🇭",
    "alpha-2": "GH",
    name: "Ghana",
  },
  {
    "dial code": "+234",
    flag: "🇳🇬",
    "alpha-2": "NG",
    name: "Nigeria",
  },
  {
    "dial code": "+235",
    flag: "🇹🇩",
    "alpha-2": "TD",
    name: "Chad",
  },
  {
    "dial code": "+236",
    flag: "🇨🇫",
    "alpha-2": "CF",
    name: "Central African Republic",
  },
  {
    "dial code": "+237",
    flag: "🇨🇲",
    "alpha-2": "CM",
    name: "Cameroon",
  },
  {
    "dial code": "+238",
    flag: "🇨🇻",
    "alpha-2": "CV",
    name: "Cape Verde",
  },
  {
    "dial code": "+239",
    flag: "🇸🇹",
    "alpha-2": "ST",
    name: "Sao Tome and Principe",
  },
  {
    "dial code": "+240",
    flag: "🇬🇶",
    "alpha-2": "GQ",
    name: "Equatorial Guinea",
  },
  {
    "dial code": "+241",
    flag: "🇬🇦",
    "alpha-2": "GA",
    name: "Gabon",
  },
  {
    "dial code": "+242",
    flag: "🇨🇬",
    "alpha-2": "CG",
    name: "Congo",
  },
  {
    "dial code": "+243",
    flag: "🇨🇩",
    "alpha-2": "CD",
    name: "Congo",
  },
  {
    "dial code": "+244",
    flag: "🇦🇴",
    "alpha-2": "AO",
    name: "Angola",
  },
  {
    "dial code": "+245",
    flag: "🇬🇼",
    "alpha-2": "GW",
    name: "Guinea-Bissau",
  },
  {
    "dial code": "+246",
    flag: "🇮🇴",
    "alpha-2": "IO",
    name: "British Indian Ocean Territory",
  },
  {
    "dial code": "+248",
    flag: "🇸🇨",
    "alpha-2": "SC",
    name: "Seychelles",
  },
  {
    "dial code": "+249",
    flag: "🇸🇩",
    "alpha-2": "SD",
    name: "Sudan",
  },
  {
    "dial code": "+250",
    flag: "🇷🇼",
    "alpha-2": "RW",
    name: "Rwanda",
  },
  {
    "dial code": "+251",
    flag: "🇪🇹",
    "alpha-2": "ET",
    name: "Ethiopia",
  },
  {
    "dial code": "+252",
    flag: "🇸🇴",
    "alpha-2": "SO",
    name: "Somalia",
  },
  {
    "dial code": "+253",
    flag: "🇩🇯",
    "alpha-2": "DJ",
    name: "Djibouti",
  },
  {
    "dial code": "+254",
    flag: "🇰🇪",
    "alpha-2": "KE",
    name: "Kenya",
  },
  {
    "dial code": "+255",
    flag: "🇹🇿",
    "alpha-2": "TZ",
    name: "Tanzania",
  },
  {
    "dial code": "+256",
    flag: "🇺🇬",
    "alpha-2": "UG",
    name: "Uganda",
  },
  {
    "dial code": "+257",
    flag: "🇧🇮",
    "alpha-2": "BI",
    name: "Burundi",
  },
  {
    "dial code": "+258",
    flag: "🇲🇿",
    "alpha-2": "MZ",
    name: "Mozambique",
  },
  {
    "dial code": "+260",
    flag: "🇿🇲",
    "alpha-2": "ZM",
    name: "Zambia",
  },
  {
    "dial code": "+261",
    flag: "🇲🇬",
    "alpha-2": "MG",
    name: "Madagascar",
  },
  {
    "dial code": "+262",
    flag: "🇹🇫",
    "alpha-2": "TF",
    name: "French Southern Territories",
  },
  {
    "dial code": "+262",
    flag: "🇾🇹",
    "alpha-2": "YT",
    name: "Mayotte",
  },
  {
    "dial code": "+262",
    flag: "🇷🇪",
    "alpha-2": "RE",
    name: "Reunion",
  },
  {
    "dial code": "+263",
    flag: "🇿🇼",
    "alpha-2": "ZW",
    name: "Zimbabwe",
  },
  {
    "dial code": "+264",
    flag: "🇳🇦",
    "alpha-2": "NA",
    name: "Namibia",
  },
  {
    "dial code": "+265",
    flag: "🇲🇼",
    "alpha-2": "MW",
    name: "Malawi",
  },
  {
    "dial code": "+266",
    flag: "🇱🇸",
    "alpha-2": "LS",
    name: "Lesotho",
  },
  {
    "dial code": "+267",
    flag: "🇧🇼",
    "alpha-2": "BW",
    name: "Botswana",
  },
  {
    "dial code": "+268",
    flag: "🇸🇿",
    "alpha-2": "SZ",
    name: "Swaziland",
  },
  {
    "dial code": "+269",
    flag: "🇰🇲",
    "alpha-2": "KM",
    name: "Comoros",
  },
  {
    "dial code": "+27",
    flag: "🇿🇦",
    "alpha-2": "ZA",
    name: "South Africa",
  },
  {
    "dial code": "+290",
    flag: "🇸🇭",
    "alpha-2": "SH",
    name: "Saint Helena",
  },
  {
    "dial code": "+291",
    flag: "🇪🇷",
    "alpha-2": "ER",
    name: "Eritrea",
  },
  {
    "dial code": "+297",
    flag: "🇦🇼",
    "alpha-2": "AW",
    name: "Aruba",
  },
  {
    "dial code": "+298",
    flag: "🇫🇴",
    "alpha-2": "FO",
    name: "Faroe Islands",
  },
  {
    "dial code": "+299",
    flag: "🇬🇱",
    "alpha-2": "GL",
    name: "Greenland",
  },
  {
    "dial code": "+30",
    flag: "🇬🇷",
    "alpha-2": "GR",
    name: "Greece",
  },
  {
    "dial code": "+31",
    flag: "🇳🇱",
    "alpha-2": "NL",
    name: "Netherlands",
  },
  {
    "dial code": "+32",
    flag: "🇧🇪",
    "alpha-2": "BE",
    name: "Belgium",
  },
  {
    "dial code": "+33",
    flag: "🇫🇷",
    "alpha-2": "FR",
    name: "France",
  },
  {
    "dial code": "+34",
    flag: "🇪🇸",
    "alpha-2": "ES",
    name: "Spain",
  },
  {
    "dial code": "+345",
    flag: "🇰🇾",
    "alpha-2": "KY",
    name: "Cayman Islands",
  },
  {
    "dial code": "+350",
    flag: "🇬🇮",
    "alpha-2": "GI",
    name: "Gibraltar",
  },
  {
    "dial code": "+351",
    flag: "🇵🇹",
    "alpha-2": "PT",
    name: "Portugal",
  },
  {
    "dial code": "+352",
    flag: "🇱🇺",
    "alpha-2": "LU",
    name: "Luxembourg",
  },
  {
    "dial code": "+353",
    flag: "🇮🇪",
    "alpha-2": "IE",
    name: "Ireland",
  },
  {
    "dial code": "+354",
    flag: "🇮🇸",
    "alpha-2": "IS",
    name: "Iceland",
  },
  {
    "dial code": "+355",
    flag: "🇦🇱",
    "alpha-2": "AL",
    name: "Albania",
  },
  {
    "dial code": "+356",
    flag: "🇲🇹",
    "alpha-2": "MT",
    name: "Malta",
  },
  {
    "dial code": "+357",
    flag: "🇨🇾",
    "alpha-2": "CY",
    name: "Cyprus",
  },
  {
    "dial code": "+358",
    flag: "🇦🇽",
    "alpha-2": "AX",
    name: "Åland Islands",
  },
  {
    "dial code": "+358",
    flag: "🇫🇮",
    "alpha-2": "FI",
    name: "Finland",
  },
  {
    "dial code": "+359",
    flag: "🇧🇬",
    "alpha-2": "BG",
    name: "Bulgaria",
  },
  {
    "dial code": "+36",
    flag: "🇭🇺",
    "alpha-2": "HU",
    name: "Hungary",
  },
  {
    "dial code": "+370",
    flag: "🇱🇹",
    "alpha-2": "LT",
    name: "Lithuania",
  },
  {
    "dial code": "+371",
    flag: "🇱🇻",
    "alpha-2": "LV",
    name: "Latvia",
  },
  {
    "dial code": "+372",
    flag: "🇪🇪",
    "alpha-2": "EE",
    name: "Estonia",
  },
  {
    "dial code": "+373",
    flag: "🇲🇩",
    "alpha-2": "MD",
    name: "Moldova",
  },
  {
    "dial code": "+374",
    flag: "🇦🇲",
    "alpha-2": "AM",
    name: "Armenia",
  },
  {
    "dial code": "+375",
    flag: "🇧🇾",
    "alpha-2": "BY",
    name: "Belarus",
  },
  {
    "dial code": "+376",
    flag: "🇦🇩",
    "alpha-2": "AD",
    name: "Andorra",
  },
  {
    "dial code": "+377",
    flag: "🇲🇨",
    "alpha-2": "MC",
    name: "Monaco",
  },
  {
    "dial code": "+378",
    flag: "🇸🇲",
    "alpha-2": "SM",
    name: "San Marino",
  },
  {
    "dial code": "+379",
    flag: "🇻🇦",
    "alpha-2": "VA",
    name: "Holy See (Vatican City State)",
  },
  {
    "dial code": "+380",
    flag: "🇺🇦",
    "alpha-2": "UA",
    name: "Ukraine",
  },
  {
    "dial code": "+381",
    flag: "🇷🇸",
    "alpha-2": "RS",
    name: "Serbia",
  },
  {
    "dial code": "+382",
    flag: "🇲🇪",
    "alpha-2": "ME",
    name: "Montenegro",
  },
  {
    "dial code": "+383",
    flag: "🇽🇰",
    "alpha-2": "XK",
    name: "Kosovo",
  },
  {
    "dial code": "+385",
    flag: "🇭🇷",
    "alpha-2": "HR",
    name: "Croatia",
  },
  {
    "dial code": "+386",
    flag: "🇸🇮",
    "alpha-2": "SI",
    name: "Slovenia",
  },
  {
    "dial code": "+387",
    flag: "🇧🇦",
    "alpha-2": "BA",
    name: "Bosnia and Herzegovina",
  },
  {
    "dial code": "+389",
    flag: "🇲🇰",
    "alpha-2": "MK",
    name: "North Macedonia",
  },
  {
    "dial code": "+39",
    flag: "🇮🇹",
    "alpha-2": "IT",
    name: "Italy",
  },
  {
    "dial code": "+40",
    flag: "🇷🇴",
    "alpha-2": "RO",
    name: "Romania",
  },
  {
    "dial code": "+41",
    flag: "🇨🇭",
    "alpha-2": "CH",
    name: "Switzerland",
  },
  {
    "dial code": "+420",
    flag: "🇨🇿",
    "alpha-2": "CZ",
    name: "Czech Republic",
  },
  {
    "dial code": "+421",
    flag: "🇸🇰",
    "alpha-2": "SK",
    name: "Slovakia",
  },
  {
    "dial code": "+423",
    flag: "🇱🇮",
    "alpha-2": "LI",
    name: "Liechtenstein",
  },
  {
    "dial code": "+43",
    flag: "🇦🇹",
    "alpha-2": "AT",
    name: "Austria",
  },
  {
    "dial code": "+44",
    flag: "🇬🇬",
    "alpha-2": "GG",
    name: "Guernsey",
  },
  {
    "dial code": "+44",
    flag: "🇮🇲",
    "alpha-2": "IM",
    name: "Isle of Man",
  },
  {
    "dial code": "+44",
    flag: "🇯🇪",
    "alpha-2": "JE",
    name: "Jersey",
  },
  {
    "dial code": "+44",
    flag: "🇬🇧",
    "alpha-2": "GB",
    name: "United Kingdom",
  },
  {
    "dial code": "+45",
    flag: "🇩🇰",
    "alpha-2": "DK",
    name: "Denmark",
  },
  {
    "dial code": "+46",
    flag: "🇸🇪",
    "alpha-2": "SE",
    name: "Sweden",
  },
  {
    "dial code": "+47",
    flag: "🇧🇻",
    "alpha-2": "BV",
    name: "Bouvet Island",
  },
  {
    "dial code": "+47",
    flag: "🇳🇴",
    "alpha-2": "NO",
    name: "Norway",
  },
  {
    "dial code": "+47",
    flag: "🇸🇯",
    "alpha-2": "SJ",
    name: "Svalbard and Jan Mayen",
  },
  {
    "dial code": "+48",
    flag: "🇵🇱",
    "alpha-2": "PL",
    name: "Poland",
  },
  {
    "dial code": "+49",
    flag: "🇩🇪",
    "alpha-2": "DE",
    name: "Germany",
  },
  {
    "dial code": "+500",
    flag: "🇫🇰",
    "alpha-2": "FK",
    name: "Falkland Islands (Malvinas)",
  },
  {
    "dial code": "+500",
    flag: "🇬🇸",
    "alpha-2": "GS",
    name: "South Georgia and the South Sandwich Islands",
  },
  {
    "dial code": "+501",
    flag: "🇧🇿",
    "alpha-2": "BZ",
    name: "Belize",
  },
  {
    "dial code": "+502",
    flag: "🇬🇹",
    "alpha-2": "GT",
    name: "Guatemala",
  },
  {
    "dial code": "+503",
    flag: "🇸🇻",
    "alpha-2": "SV",
    name: "El Salvador",
  },
  {
    "dial code": "+504",
    flag: "🇭🇳",
    "alpha-2": "HN",
    name: "Honduras",
  },
  {
    "dial code": "+505",
    flag: "🇳🇮",
    "alpha-2": "NI",
    name: "Nicaragua",
  },
  {
    "dial code": "+506",
    flag: "🇨🇷",
    "alpha-2": "CR",
    name: "Costa Rica",
  },
  {
    "dial code": "+507",
    flag: "🇵🇦",
    "alpha-2": "PA",
    name: "Panama",
  },
  {
    "dial code": "+508",
    flag: "🇵🇲",
    "alpha-2": "PM",
    name: "Saint Pierre and Miquelon",
  },
  {
    "dial code": "+509",
    flag: "🇭🇹",
    "alpha-2": "HT",
    name: "Haiti",
  },
  {
    "dial code": "+51",
    flag: "🇵🇪",
    "alpha-2": "PE",
    name: "Peru",
  },
  {
    "dial code": "+52",
    flag: "🇲🇽",
    "alpha-2": "MX",
    name: "Mexico",
  },
  {
    "dial code": "+53",
    flag: "🇨🇺",
    "alpha-2": "CU",
    name: "Cuba",
  },
  {
    "dial code": "+54",
    flag: "🇦🇷",
    "alpha-2": "AR",
    name: "Argentina",
  },
  {
    "dial code": "+55",
    flag: "🇧🇷",
    "alpha-2": "BR",
    name: "Brazil",
  },
  {
    "dial code": "+56",
    flag: "🇨🇱",
    "alpha-2": "CL",
    name: "Chile",
  },
  {
    "dial code": "+57",
    flag: "🇨🇴",
    "alpha-2": "CO",
    name: "Colombia",
  },
  {
    "dial code": "+58",
    flag: "🇻🇪",
    "alpha-2": "VE",
    name: "Venezuela",
  },
  {
    "dial code": "+590",
    flag: "🇬🇵",
    "alpha-2": "GP",
    name: "Guadeloupe",
  },
  {
    "dial code": "+590",
    flag: "🇧🇱",
    "alpha-2": "BL",
    name: "Saint Barthelemy",
  },
  {
    "dial code": "+590",
    flag: "🇲🇫",
    "alpha-2": "MF",
    name: "Saint Martin",
  },
  {
    "dial code": "+591",
    flag: "🇧🇴",
    "alpha-2": "BO",
    name: "Bolivia",
  },
  {
    "dial code": "+592",
    flag: "🇬🇾",
    "alpha-2": "GY",
    name: "Guyana",
  },
  {
    "dial code": "+593",
    flag: "🇪🇨",
    "alpha-2": "EC",
    name: "Ecuador",
  },
  {
    "dial code": "+594",
    flag: "🇬🇫",
    "alpha-2": "GF",
    name: "French Guiana",
  },
  {
    "dial code": "+595",
    flag: "🇵🇾",
    "alpha-2": "PY",
    name: "Paraguay",
  },
  {
    "dial code": "+596",
    flag: "🇲🇶",
    "alpha-2": "MQ",
    name: "Martinique",
  },
  {
    "dial code": "+597",
    flag: "🇸🇷",
    "alpha-2": "SR",
    name: "Suriname",
  },
  {
    "dial code": "+598",
    flag: "🇺🇾",
    "alpha-2": "UY",
    name: "Uruguay",
  },
  {
    "dial code": "+599",
    flag: "",
    "alpha-2": "AN",
    name: "Netherlands Antilles",
  },
  {
    "dial code": "+60",
    flag: "🇲🇾",
    "alpha-2": "MY",
    name: "Malaysia",
  },
  {
    "dial code": "+61",
    flag: "🇦🇺",
    "alpha-2": "AU",
    name: "Australia",
  },
  {
    "dial code": "+61",
    flag: "🇨🇽",
    "alpha-2": "CX",
    name: "Christmas Island",
  },
  {
    "dial code": "+61",
    flag: "🇨🇨",
    "alpha-2": "CC",
    name: "Cocos (Keeling) Islands",
  },
  {
    "dial code": "+62",
    flag: "🇮🇩",
    "alpha-2": "ID",
    name: "Indonesia",
  },
  {
    "dial code": "+63",
    flag: "🇵🇭",
    "alpha-2": "PH",
    name: "Philippines",
  },
  {
    "dial code": "+64",
    flag: "🇳🇿",
    "alpha-2": "NZ",
    name: "New Zealand",
  },
  {
    "dial code": "+64",
    flag: "🇵🇳",
    "alpha-2": "PN",
    name: "Pitcairn",
  },
  {
    "dial code": "+65",
    flag: "🇸🇬",
    "alpha-2": "SG",
    name: "Singapore",
  },
  {
    "dial code": "+66",
    flag: "🇹🇭",
    "alpha-2": "TH",
    name: "Thailand",
  },
  {
    "dial code": "+670",
    flag: "🇹🇱",
    "alpha-2": "TL",
    name: "Timor-Leste",
  },
  {
    "dial code": "+672",
    flag: "🇦🇶",
    "alpha-2": "AQ",
    name: "Antarctica",
  },
  {
    "dial code": "+672",
    flag: "🇭🇲",
    "alpha-2": "HM",
    name: "Heard Island and Mcdonald Islands",
  },
  {
    "dial code": "+672",
    flag: "🇳🇫",
    "alpha-2": "NF",
    name: "Norfolk Island",
  },
  {
    "dial code": "+673",
    flag: "🇧🇳",
    "alpha-2": "BN",
    name: "Brunei Darussalam",
  },
  {
    "dial code": "+674",
    flag: "🇳🇷",
    "alpha-2": "NR",
    name: "Nauru",
  },
  {
    "dial code": "+675",
    flag: "🇵🇬",
    "alpha-2": "PG",
    name: "Papua New Guinea",
  },
  {
    "dial code": "+676",
    flag: "🇹🇴",
    "alpha-2": "TO",
    name: "Tonga",
  },
  {
    "dial code": "+677",
    flag: "🇸🇧",
    "alpha-2": "SB",
    name: "Solomon Islands",
  },
  {
    "dial code": "+678",
    flag: "🇻🇺",
    "alpha-2": "VU",
    name: "Vanuatu",
  },
  {
    "dial code": "+679",
    flag: "🇫🇯",
    "alpha-2": "FJ",
    name: "Fiji",
  },
  {
    "dial code": "+680",
    flag: "🇵🇼",
    "alpha-2": "PW",
    name: "Palau",
  },
  {
    "dial code": "+681",
    flag: "🇼🇫",
    "alpha-2": "WF",
    name: "Wallis and Futuna",
  },
  {
    "dial code": "+682",
    flag: "🇨🇰",
    "alpha-2": "CK",
    name: "Cook Islands",
  },
  {
    "dial code": "+683",
    flag: "🇳🇺",
    "alpha-2": "NU",
    name: "Niue",
  },
  {
    "dial code": "+685",
    flag: "🇼🇸",
    "alpha-2": "WS",
    name: "Samoa",
  },
  {
    "dial code": "+686",
    flag: "🇰🇮",
    "alpha-2": "KI",
    name: "Kiribati",
  },
  {
    "dial code": "+687",
    flag: "🇳🇨",
    "alpha-2": "NC",
    name: "New Caledonia",
  },
  {
    "dial code": "+688",
    flag: "🇹🇻",
    "alpha-2": "TV",
    name: "Tuvalu",
  },
  {
    "dial code": "+689",
    flag: "🇵🇫",
    "alpha-2": "PF",
    name: "French Polynesia",
  },
  {
    "dial code": "+690",
    flag: "🇹🇰",
    "alpha-2": "TK",
    name: "Tokelau",
  },
  {
    "dial code": "+691",
    flag: "🇫🇲",
    "alpha-2": "FM",
    name: "Micronesia",
  },
  {
    "dial code": "+692",
    flag: "🇲🇭",
    "alpha-2": "MH",
    name: "Marshall Islands",
  },
  {
    "dial code": "+7",
    flag: "🇰🇿",
    "alpha-2": "KZ",
    name: "Kazakhstan",
  },
  {
    "dial code": "+7",
    flag: "🇷🇺",
    "alpha-2": "RU",
    name: "Russia",
  },
  {
    "dial code": "+81",
    flag: "🇯🇵",
    "alpha-2": "JP",
    name: "Japan",
  },
  {
    "dial code": "+82",
    flag: "🇰🇷",
    "alpha-2": "KR",
    name: "Korea",
  },
  {
    "dial code": "+84",
    flag: "🇻🇳",
    "alpha-2": "VN",
    name: "Vietnam",
  },
  {
    "dial code": "+850",
    flag: "🇰🇵",
    "alpha-2": "KP",
    name: "Korea",
  },
  {
    "dial code": "+852",
    flag: "🇭🇰",
    "alpha-2": "HK",
    name: "Hong Kong",
  },
  {
    "dial code": "+853",
    flag: "🇲🇴",
    "alpha-2": "MO",
    name: "Macao",
  },
  {
    "dial code": "+855",
    flag: "🇰🇭",
    "alpha-2": "KH",
    name: "Cambodia",
  },
  {
    "dial code": "+856",
    flag: "🇱🇦",
    "alpha-2": "LA",
    name: "Laos",
  },
  {
    "dial code": "+86",
    flag: "🇨🇳",
    "alpha-2": "CN",
    name: "China",
  },
  {
    "dial code": "+880",
    flag: "🇧🇩",
    "alpha-2": "BD",
    name: "Bangladesh",
  },
  {
    "dial code": "+886",
    flag: "🇹🇼",
    "alpha-2": "TW",
    name: "Taiwan",
  },
  {
    "dial code": "+90",
    flag: "🇹🇷",
    "alpha-2": "TR",
    name: "Türkiye",
  },
  {
    "dial code": "+91",
    flag: "🇮🇳",
    "alpha-2": "IN",
    name: "India",
  },
  {
    "dial code": "+92",
    flag: "🇵🇰",
    "alpha-2": "PK",
    name: "Pakistan",
  },
  {
    "dial code": "+93",
    flag: "🇦🇫",
    "alpha-2": "AF",
    name: "Afghanistan",
  },
  {
    "dial code": "+94",
    flag: "🇱🇰",
    "alpha-2": "LK",
    name: "Sri Lanka",
  },
  {
    "dial code": "+95",
    flag: "🇲🇲",
    "alpha-2": "MM",
    name: "Myanmar",
  },
  {
    "dial code": "+960",
    flag: "🇲🇻",
    "alpha-2": "MV",
    name: "Maldives",
  },
  {
    "dial code": "+961",
    flag: "🇱🇧",
    "alpha-2": "LB",
    name: "Lebanon",
  },
  {
    "dial code": "+962",
    flag: "🇯🇴",
    "alpha-2": "JO",
    name: "Jordan",
  },
  {
    "dial code": "+963",
    flag: "🇸🇾",
    "alpha-2": "SY",
    name: "Syrian Arab Republic",
  },
  {
    "dial code": "+964",
    flag: "🇮🇶",
    "alpha-2": "IQ",
    name: "Iraq",
  },
  {
    "dial code": "+965",
    flag: "🇰🇼",
    "alpha-2": "KW",
    name: "Kuwait",
  },
  {
    "dial code": "+966",
    flag: "🇸🇦",
    "alpha-2": "SA",
    name: "Saudi Arabia",
  },
  {
    "dial code": "+967",
    flag: "🇾🇪",
    "alpha-2": "YE",
    name: "Yemen",
  },
  {
    "dial code": "+968",
    flag: "🇴🇲",
    "alpha-2": "OM",
    name: "Oman",
  },
  {
    "dial code": "+970",
    flag: "🇵🇸",
    "alpha-2": "PS",
    name: "Palestinian Territory",
  },
  {
    "dial code": "+971",
    flag: "🇦🇪",
    "alpha-2": "AE",
    name: "United Arab Emirates",
  },
  {
    "dial code": "+972",
    flag: "🇮🇱",
    "alpha-2": "IL",
    name: "Israel",
  },
  {
    "dial code": "+973",
    flag: "🇧🇭",
    "alpha-2": "BH",
    name: "Bahrain",
  },
  {
    "dial code": "+974",
    flag: "🇶🇦",
    "alpha-2": "QA",
    name: "Qatar",
  },
  {
    "dial code": "+975",
    flag: "🇧🇹",
    "alpha-2": "BT",
    name: "Bhutan",
  },
  {
    "dial code": "+976",
    flag: "🇲🇳",
    "alpha-2": "MN",
    name: "Mongolia",
  },
  {
    "dial code": "+977",
    flag: "🇳🇵",
    "alpha-2": "NP",
    name: "Nepal",
  },
  {
    "dial code": "+98",
    flag: "🇮🇷",
    "alpha-2": "IR",
    name: "Iran",
  },
  {
    "dial code": "+992",
    flag: "🇹🇯",
    "alpha-2": "TJ",
    name: "Tajikistan",
  },
  {
    "dial code": "+993",
    flag: "🇹🇲",
    "alpha-2": "TM",
    name: "Turkmenistan",
  },
  {
    "dial code": "+994",
    flag: "🇦🇿",
    "alpha-2": "AZ",
    name: "Azerbaijan",
  },
  {
    "dial code": "+995",
    flag: "🇬🇪",
    "alpha-2": "GE",
    name: "Georgia",
  },
  {
    "dial code": "+996",
    flag: "🇰🇬",
    "alpha-2": "KG",
    name: "Kyrgyzstan",
  },
  {
    "dial code": "+998",
    flag: "🇺🇿",
    "alpha-2": "UZ",
    name: "Uzbekistan",
  },
];
